### PR TITLE
Radar units

### PR DESCRIPTION
**Pull request by dopplershift**
Fix up units for radar support (since UDUNITS is the standard for CF).
- Add "Bz" as an acceptable unit (alongside "BZ"), and make description spell it consistently and correctly
- Add dB (used for differential reflectivity)

### CODE REVIEW

**Comment by ocefpaf** [comment]
Awesome! :+1:

**Comment by josephhardinee** [comment]
+1

**Comment by mhidas** [comment]
:+1: Any chance of this getting merged?

Also, would this allow the unit "decibel" to be recognised, or does it have to be written as "dB"?

**Comment by pelson** [comment]
@semmerson, sorry to bother you directly, but any update on https://github.com/Unidata/UDUNITS-2/issues/33#issuecomment-439085223? (I'm assuming that you meant "think about" this PR, so apologies if I've completely got the wrong end of the stick)

**Comment by d70-t** [comment]
👍

**Review by semmerson — APPROVED** [review]

**Pull request merged**
